DROP TABLE IF EXISTS ANIME;
DROP TABLE IF EXISTS USER;
CREATE TABLE ANIME (ID INT IDENTITY PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE USER (ID INT IDENTITY PRIMARY KEY, NAME VARCHAR(255), USERNAME VARCHAR(255), PASSWORD VARCHAR(255), AUTHORITIES VARCHAR(255));